site:
  name: TNX6 Twitch
  site: 'https://tnx6.github.io/'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

metadata:
  title:
    default: TNX6 Twitch
    template: '%s — AstroWind'
  description: "A personal website to show off all relevant infos for my Twitch stream."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: TNX6 Twitch
    images:
      - url: '/assets/default.png'
        width: 1200
        height: 630
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
